### ISSUE TITLE
💬 Criação do método excluir

### ISSUE THREAD

**Issue by BispoJPM** [Porygonn/Porygon#47]
- Criar o método excluir, onde deletará permanentemente o registro suspeito;
- Criar um aviso "pop-up" dizendo que a ação será permanente e irreversível.

**Comment by Glei-Rezende** [comment]
Para atender às orientações do cliente no projeto, vamos detalhar as etapas das tarefas necessárias para permitir que o pesquisador altere, restaure e exclua dados irregulares, garantindo a precisão, integridade, confiabilidade e rastreabilidade dos registros no sistema. 
1)	Design do Sistema
•	Modelagem de dados, atualizar o esquema do banco de dados para suportar operações de alteração restauração e exclusão de registros.
•	Incluir campos necessários para rastreabilidade, como “deleted_at”, “restored_at”, e “modified_at”.
•	Desing da interface de Usuário, permitir ao pesquisador executar essas ações de forma intuitiva e segura. Isso inclui a criação de telas para exibir, alterar, restaurar e excluir dados, bem como o desingn do “pop-up”de confirmação.

2)	Desenvolvimento, método excluir
a.	Criação do método de exclusão, desenvolver o método para deletar permanentemente registros suspeitos.
Selecionar campo, clicar no campo e botões de ação;
b.	Clicar em excluir, criar o pop-up para exclusão, alerta o usuário de que a ação será permanente e irreversível;
c.	Perguntar se deve excluir (Dados irregulares), confirmar;
d.	Fecha o pop-up;
